services:
  superset:
    build: ./superset
    ports:
      - "8089:8088"
    volumes:
      - ./data:/data
      - superset_home:/app/superset_home
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY:-clave-temporal-solo-desarrollo-local}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - SUPERSET_ALLOWED_SCHEMAS=${SUPERSET_ALLOWED_SCHEMAS:-sieej.mart}
    restart: unless-stopped

volumes:
  superset_home:
